### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Boone777** [edjroot/webext-save-to-folder#6]
I can't make it work in  Firefox
I have tried every option I could think of. 
I would really like this to work it woul d be very practicle for me.

Does the simlink has to be in the default download folder ? That's what I did anyway.
It just does nothing or sometimes I have a Firefox  debug page poping up.
It seems pretty simple to operate but somehow it does'nt work for me. 

The symlink works well by itself.

**Comment by edjroot** [comment]
Hey, Boone777! Thanks for your feedback. I'm sorry the extension is not working for you.

I'm not sure I understand what problem you're having. You can't make the extension work at all? Or is the issue just with the symlinks? In any case, I just tested the extension here and it works.

Yes, the symlink must be in your default downloads folder, but it can point to any other location.

Would you mind sharing a few details, such as your OS, Firefox version, the list of folders configured in the extension, a screenshot of the Firefox debug page and the name of the symlink in question?

**Comment by Boone777** [comment]
Thanks for answering.  I can't make it work at all but I blame the symlink wich for whatever reason, it seems hard to create on my computer. There is some restrictions with some folders, I can't create them wherever I want. 
https://imgur.com/9jBP2y3

Folder list: https://imgur.com/v1imdfy

It might have something to do with this.

Win7, Firefox Quantum 68.0.2  

Now the Firefox debug does'nt always show up I can't reproduce right now but I made a gif but nothing happens when clicking the link so not much to show there.  
At the end of the gift I show the commands in terminal some destination folders work some don't.

https://imgur.com/211GuYN

**Comment by Boone777** [comment]
The link was wrongly made  in the extension. I now put the right one from the download folder.
The debug showed up: https://i.imgur.com/r8nnt4i.png
Only when downloading from youtube wich also uses another extension to show download links.

But still nothing happens on other sites.

Does'nt work for me in chrome either.

**Comment by edjroot** [comment]
Really sorry for the delay.

> There is some restrictions with some folders, I can't create them wherever I want.

I think you just need to put the second address between quotes. That's because there's whitespace in it.
So this should work: `mklink /d C:\Users\Boone\Downloads\JBP "E:\The Work\Jordan Peterson"`

> I now put the right one from the download folder.

Since you did it, could you show me your folder list again?
And what extension are you using for downloading YouTube videos?

Sorry again for the delay and thanks for the info.

**Comment by edjroot** [comment]
Closing for now, but feel free to reopen it if you still need help.
